### ISSUE TITLE
Using with create-react-app

### ISSUE THREAD

**Issue by anotheri** [sindresorhus/slugify#19]
Trying to use it with create-react-app, it fails the minification:

```
Failed to minify the code from this file:

 	./node_modules/@sindresorhus/slugify/index.js:7

Read more here: http://bit.ly/2tRViJ9
```

**Comment by sindresorhus** [comment]
Upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
