### ISSUE TITLE
Failed to minify the code from this file:  ./node_modules/@sindresorhus/slugify/index.js:7

### ISSUE THREAD

**Issue by hbl-huongdv** [sindresorhus/slugify#21]

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser and with Uglify. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by sindresorhus** [comment]
Or you could use https://github.com/terser-js/terser

**Comment by hbl-huongdv** [comment]
Thanks
