### ISSUE TITLE
Why CLI is not included?

### ISSUE THREAD

**Issue by roipoussiere** [sindresorhus/slugify#24]
Why the [CLI](https://github.com/sindresorhus/slugify-cli) for this module is not included in the repo? It could be useful to have both interfaces in one place and doesn't really increase the module size.

**Comment by sindresorhus** [comment]
> and doesn't really increase the module size.

It does. That's one of the reasons they are split.

See https://github.com/sindresorhus/ama/issues/17 for more info.
