### ISSUE TITLE
Wrong generated slug

### ISSUE THREAD

**Issue by screendriver** [sindresorhus/slugify#25]
`What the JAMstack means` becomes `what-the-ja-mstack-means`

**Comment by matheusazzi** [comment]
I believe for that scenario you should use:
```js
slugify('What the JAMstack means', { decamelize: false })
=> "what-the-jamstack-means"
```

**Comment by abnersajr** [comment]
@matheusazzi paste the solution for your scenario. ⏫ 

### Why does this happen?

This function has an option [decamelize](https://github.com/sindresorhus/slugify#decamelize).
It looks for a capital letter followed by a tiny and split.

**Comment by screendriver** [comment]
Thank you @matheusazzi 👍 I overlooked that setting.
