### ISSUE TITLE
How to not remove brackets?

### ISSUE THREAD

**Issue by stevecohenfr** [sindresorhus/slugify#26]
I tried 

```
customReplacements: [
                ['[', '['],
                [']', ']']
            ]
```
to force not remove brackets [] but still removed in my slugified string...

**Comment by sindresorhus** [comment]
What's the use-case? This probably is the same as https://github.com/sindresorhus/slugify/issues/40#issuecomment-569683199. Slugify is meant to create a valid URL component.

**Comment by stevecohenfr** [comment]
I really don't remember the use case, it was 1 year ago, I think I found another way ;)
Thanks for your answer !
