### ISSUE TITLE
Incorrect dashes

### ISSUE THREAD

**Issue by paleite** [sindresorhus/slugify#31]
`slugify('XBOX360');` returns "xbo-x360". But I expected the value to be "xbox360"

**Comment by kainiedziela** [comment]
You should pass a following options param: `{ decamelize: false}`.

**Comment by TiagoDanin** [comment]
![image](https://user-images.githubusercontent.com/5731176/58902757-1e3fc900-86da-11e9-8eab-9c695a48d935.png)
https://runkit.com/tiagodanin/5cf6b2894117be001aa4a297 No problem here...

**Comment by paleite** [comment]
Thanks, but that’s not the same dependency.
This issue is about `@sindresorhus/slugify`: https://runkit.com/paleite/5cffe6e38b563f001ac2d5ea

**Comment by 0x0480** [comment]
Same issue with "3D" it returns 3-d lol

**Comment by notlmn** [comment]
As mentioned by @kainiedziela, use `{decamelize: false}`.

![image](https://user-images.githubusercontent.com/37769974/60598640-aba23600-9dca-11e9-8129-60e75fcef9b7.png)
