### ISSUE TITLE
The library doesn't support IE 11

### ISSUE THREAD

**Issue by Max-Kuzomko** [sindresorhus/slugify#32]
We got the following errors in IE11:
1. Target is not iterable + TypeError
2. Object does not support property or method "Symbol(Symbol.iterator
3. Object does not support property or method "normalize""

**Comment by ApacheEx** [comment]
Candidates to replace:

1.`for (const [key, value] of replacements)` - can be rewritten to `Object.keys`
2. `new Map([` - can be used simple `Object`.
3. `string.normalize` - looks like need to use https://github.com/walling/unorm/

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by ApacheEx** [comment]
Thanks for replying. We already use `"react-scripts": "3.0.1"` with the following browserlist:

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

and somehow it still doesn't work properly. Also we have 
```
import 'react-app-polyfill/ie11';
```
as first line of `src/index.js`
