### ISSUE TITLE
Ignores Turkish Character

### ISSUE THREAD

**Issue by erdidoqan** [sindresorhus/slugify#33]
Have the same characters like 'Ö' and 'ö' in German and Turkish. How can we fix this?

**Comment by 0x0480** [comment]
This script can't detect text's lang.
Just add chars manually to end of replacement.js
`,
	['ü', 'u'],
	['Ü', 'u'],
	['ö', 'o'],
	['Ö', 'o'],`

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/transliterate/issues/2, which is a more general solution to this problem.
