### ISSUE TITLE
Removing of '/' character

### ISSUE THREAD

**Issue by naveensky** [sindresorhus/slugify#40]
Hi, 

Does the library remove `/` character from the path? I want to move certain pages as a sub-directory of main path, like `integrations/abc` and then have an original `integrations` page as well. 

Is it possible with slufigy?

**Comment by TiagoDanin** [comment]
[Slug](https://en.wikipedia.org/wiki/Clean_URL) convert a string into a valid URL identifier. 

```js
const string = 'abc/d&f/ghi#home@user/' 
const output = string.split('/').map(slugify).join('/')
```
