### ISSUE TITLE
Extract transliteration into it's own library

### ISSUE THREAD

**Issue by slavafomin** [sindresorhus/slugify#44]
Hello!

Thank you for this great library!

However, would you consider to extract the transliteration part into it's own library? I believe this functionality could be very much useful on it's own.

**Comment by sindresorhus** [comment]
Yeah, I have that on my todo list, but thanks for the push. I'll work on it tomorrow.

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/transliterate :)

**Comment by slavafomin** [comment]
That's cool, thanks!
