### ISSUE TITLE
Error: "Expected identifier, string or number" on Edge-18

### ISSUE THREAD

**Issue by vbartusevicius** [sindresorhus/slugify#47]
On latest Edge-18 I'm getting this error: "Expected identifier, string or number".
To see it, please go to https://x5e7o.csb.app/ with Edge-18 - this is the output from https://codesandbox.io/s/distracted-elgamal-x5e7o.

Basically it complains about the spread operators in `slugify/index.js`. I don't see any supported platforms by this package, but could it be possible to support latest Edge-18 ?

**Comment by eseQ** [comment]
@vbartusevicius wait for merge PR =)

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in supporting Edge 18.

**Comment by vbartusevicius** [comment]
@sindresorhus could you tell why? It's just a matter of spread vs Object.assign. Even when somebody already submitter PR

**Comment by eseQ** [comment]
@vbartusevicius hmmm this is strange but ok

**Comment by vbartusevicius** [comment]
I think @sindresorhus is a bit too arrogant. @eseQ - thanks for PR, but will have to look for more open-minded library.

**Comment by eseQ** [comment]
@vbartusevicius we can just be thankful for @sindresorhus open-source work. Really.
For IE support you can use [my fork](https://github.com/eseQ/slugify)
