### ISSUE TITLE
Allow empty replacement

### ISSUE THREAD

**Issue by abdonrd** [sindresorhus/slugify#52]
My use case is create usernames without separator.
Following the documentation: https://github.com/sindresorhus/slugify#separator

I have tried with:

```
slugify('BAR and baz', {separator: ''});
```

And I expect this:

```
'barandbaz'
```

But I get an error:

```
SyntaxError: Invalid regular expression: /{2,}/: Nothing to repeat
```

**Comment by sindresorhus** [comment]
Sure. PR welcome.
