### ISSUE TITLE
Make patternSlug customizable

### ISSUE THREAD

**Issue by apiel** [sindresorhus/slugify#54]
Hello,

Would it be possible to make the `patternSlug` configurable, so for example if we want to have `#` in our slug, we could do something like `slugify('foo#bar hello$123', {patternSlug: /[^a-zA-Z#\d]+/g});` to get `foo#bar-hello-123`.

Would be really amazing feature :-)

**Comment by sindresorhus** [comment]
Why do you need to ignore `#`? What's the use-case? Then it's technically no longer a slug.

**Comment by apiel** [comment]
Depends for which purpose we use the slug. We use it in our db to create some tags.

**Comment by sindresorhus** [comment]
I don't want to expose the pattern slug regex, as it's an implementation detail, and this would lock us into that way of doing it forever. I would be open to an option to preserve a set of given characters, but I think in your case, it would be simpler for you to just split it on `#`, run the parts through slugify, and then join again.
