### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by leosin** [sindresorhus/slugify#67]
Error [ERR_REQUIRE_ESM]: require() of ES Module 

`import Slugify from '@sindresorhus/slugify'`

![image](https://user-images.githubusercontent.com/3676670/158333843-2c9d0518-b0d8-4193-b486-9fc3d4b60c52.png)

`node_modules/@sindresorhus/slugify/index.js from .../vite.config.ts not supported.`

Am I doing something wrong?

https://github.com/jeremys/uslug

i use this plugin is ok
`slugify: (s: string) => uslug(s), `

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by leosin** [comment]
Thank you very much, I will read it carefully

**Comment by krazyjakee** [comment]
but this doesn't actually resolve the issue. This is a library that could be used in .js configurations which cannot be configured to run like a module or be precompiled. I work with thousands of npm libraries, this is the only one which stubbornly misunderstands the current ecosystem.

**Comment by lud** [comment]
Can this be used with eleventy?

**Comment by nezort11** [comment]
Just use this package https://github.com/simov/slugify instead of this, same API. it's not worth all the hassle with ESM modules for a single package

**Comment by YvesRijckaert** [comment]
FYI: the proposed alternative package https://github.com/simov/slugify is not working for us. Ran into issues with it not slugifying special characters.
